name: Verify

on:
  push:
    branches-ignore:
      - gh-pages
env: 
  distribution: 'zulu'

jobs:          
  verify-java-11:
    runs-on: ubuntu-latest
    env:
      java-version: 11
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java-version }}
          distribution: ${{ env.distribution }}
          cache: 'maven'
          cache-dependency-path: 'pom.xml'
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
